server:
  port: 9002
  #port: 8443
  servlet:
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值25
      min-spare: 30
    #tomcat连接超时时间
    connection-timeout: 6000
  #ssl:
    #key-store: classpath:ssl/tomcat.pkcs12
    #key-store-password: 111111
    #key-store-type: PKCS12
    #key-alias: admin
    #enabled: true
#eureka的注册中心地址
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://admin:111111@localhost:8421/eureka/
#注册进eureka的名字
spring:
  application:
    name: GeekPlusBlog
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    druid:
      username: root
      password: 111111
      url: jdbc:mysql://localhost:3306/geekplusblog?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      max-evictable-idle-time-millis: 900000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: on
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: on
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      useGlobalDataSourceStat: on
      defaultAutoCommit: on # 事物自动提交
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  devtools:
    restart:
      enabled: on  #设置开启热部署
      additional-paths: src/main/java #重启目录
  freemarker:
    check-template-location: false
  #redis配置
  redis:
    #redis服务地址 端口 密码
    host: 127.0.0.1
    port: 6379
    password: 111111
    #Redis数据库索引（默认为0）
    #database: 0
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 80
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 30
        #连接池中的最小空闲连接
        min-idle: 5
    #连接超时时间（毫秒）
    timeout: 9000
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.scheduler.instanceName: PlusScheduler
      org.quartz.scheduler.instanceId: AUTO
      #org.quartz.impl.jdbcjobstore.JobStoreTX
      #注意Spring Boot 2.5.6+版本需改用LocalDataSourceJobStore替代JobStoreTX，否则会抛出"DataSource name not set"异常
      org.quartz.jobStore.class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      org.quartz.jobStore.useProperties: false
      org.quartz.jobStore.misfireThreshold: 60000
      org.quartz.jobStore.tablePrefix: QRTZ_
      org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
      org.quartz.threadPool.threadCount: 10
  #spring提供的邮箱发送相关配置
#  mail:
#    username: GeekPlus
mybatis:
  #config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
  type-aliases-package: com.geekplus.webapp.**.entity
  configuration:
    cache-enabled: on
    use-generated-keys: on
    default-executor-type: reuse
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#Swagger配置
swagger:
  enable: true
  pathMapping: /dev-api
#security:
#  basic:
#    enable: false
#    username: geekplus
#    password: 111111
#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql
  page-size-zero: true
#  reasonable: true
token:
  expireTime: 604800 #过期时间7天
  residueRefreshTime: 86400 #最后一天
  header: Plus-Token
  secret: esbfhjbvhjbfhjvbfjhbvhjbfjhvefffe
geekplus:
  name: GeekPlus
  version: 1.0.0
  # 版权年份
  copyrightYear: 2024
  # 实例演示开关
  demoEnabled: true
  #文件路径 示例（ Windows配置D:/maike/uploadPath，Linux配置 /home/maike/uploadPath）
  profile: /home/app/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math
  #自定义邮箱发送，配置用户邮箱地址和密码以及smtp邮箱服务器地址等，根据需要做修改
  email:
    address: xxxx@qq.com
    password: 123456
    host: smtp.qq.com
    port: 587
    auth: true
    tls:
      enable: true
